<!-- HEADER & NAV     -->
<header>
   <div class="container">
       <div class="row">
           <div id="titrePrimaire" class="col-md-5">
               <h1>Aurélie Contamine</h1>
           </div>
           <div class="col-md-2" id="logoEnTete">
               <a href="index.php"><img src="../img/ACCut.png" alt="Logo-AC"></a>
           </div>
           <div id="titreSecondaire" class="col-md-5">    
               <p>- Naturopathie & Reïki -</p>
           </div>
       </div>    
   </div>
    
    <nav>
        <div class="container" id='index'>
            <a href="index.php#methodes" class='retour'> <i class="fas fa-angle-double-left"></i> Retour à l'acceuil</a>
        </div>    
    </nav>
</header>    