<?php include "templates/head.phtml" ?>
    <body> 
    <?php include "templates/headerAdmin.phtml" ?>

        <div class="rouleau">
            <!-- MES RDV  -->
            <section class="container">
                <h3>Fiche de renseignement</h3>

                <form action="update.php?id=<?=$idUser?>" method="POST">
                    <label for='lastName'>Nom :</label><input type='text' name='lastName' id='lastName' class='modif' placeholder='<?= htmlspecialchars($userInfo['lastName']); ?>'>
                    <label for='firstName'>Prénom :</label><input type='text' name='firstName' id='firtName' class='modif' placeholder='<?= htmlspecialchars($userInfo['firstName']); ?>'>
                    <label for='birthday'>Date de naissance :</label><input type='date' name='birthday' id='birthday' class='modif' placeholder='<?= htmlspecialchars($userInfo['birthday']); ?>'>
                    <label for='sex'>Sexe :</label><input type='text' name='sex' id='sex' class='modif' placeholder='<?= htmlspecialchars($userInfo['sex']); ?>'>
                    <label for='height'>Taille :</label><input type='text' name='height' class='modif' id='height' placeholder='<?= htmlspecialchars($userInfo['height']); ?>'>
                    <label for='weight'>Poids :</label><input type='text' name='weight' class='modif' id='weight' placeholder='<?= htmlspecialchars($userInfo['weight']); ?>'>
                    <label for='diet'>Régime :</label><input type='text' name='diet' class='modif' id='diet' placeholder='<?= htmlspecialchars($userInfo['diet']); ?>'>

                    <label for='email'>E-mail :</label><input type='text' name='email' class='modif' id='email' placeholder='<?= htmlspecialchars($userInfo['email']); ?>'>
                    <label for='phone'>Téléphone :</label><input type='text' name='phone' class='modif' id='phone' placeholder='<?= htmlspecialchars($userInfo['phone']); ?>'>

                    <label for='reason'>Raison de la venue :</label><input type='text' name='reason' class='modif' id='reason' placeholder='<?= htmlspecialchars($userInfo['reason']); ?>'>

                    <label for='pathology'>Pathologies :</label><textarea type='text' name='pathology' class='modif' id='pathology' rows="5"  placeholder='<?= htmlspecialchars($userInfo['pathology']); ?>'></textarea>
                    <label for='treatment'>Traitements :</label><textarea type='text' name='treatment' class='modif' id='treatment' rows="5" placeholder='<?= htmlspecialchars($userInfo['treatment']); ?>'></textarea>

                    <label for='emunctory'>Emonctoires :</label><textarea type='text' name='emunctory' class='modif' id='emunctory' rows="5"placeholder='<?= htmlspecialchars($userInfo['emunctory']); ?>'></textarea>

                    <label for='other'>Autre :</label><textarea type='text' name='other' class='modif' id='other' rows="10" placeholder='<?= htmlspecialchars($userInfo['other']); ?>'></textarea>

                    <input class='submit' type='submit' value='Enregistrer'>

                </form>

            </section>
        </div> <!--  fin de rouleau -->
        <script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>
        <script src="../js/function.js"></script>
        <script src="../js/main.js"></script>
    </body>
</html>