<?php include "templates/head.phtml" ?>
    <body> 
    <?php include "templates/headerAdmin.phtml" ?>

        <div class="rouleau">
            <!-- MES RDV  -->
            <section class="container">
                <h3>Mes rendez-vous<br><a href="addAppointment.php" style="font-family: Arial; font-size: 1rem; color: black;">(Ajouter un rendez-vous)</a></h3>
                <li>
                    <?php foreach($mesRdv as $rendezVous): ?>
                        <ul class='trashable'> <a href='ficheUser.php?id=<?= $rendezVous['user_id']?>' class='espaceAdmin-rdv'> &#x2022 <?= $rendezVous['name']?> le <?=$rendezVous['dateEu']?> à <?=$rendezVous['start_hour'] ?> avec <?=$rendezVous['firstName']?> <?=$rendezVous['lastName']?></a> <a href='rdvDelete.php?id=<?= $rendezVous['rdv_id']?>'> <i class="fas fa-trash inactif"></i></a></ul>   
                    <?php endforeach; ?>
                </li>
            </section>
        </div> <!--  fin de rouleau -->
        <script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>
        <script src="../js/function.js"></script>
        <script src="../js/main.js"></script>
    </body>
</html>