<?php include "templates/head.phtml" ?>
    <body> 
        <header>
            <div class="container">
                <div class="row">
                    <div id="titrePrimaire" class="col-md-5">
                        <h1>Aurélie Contamine</h1>
                    </div>
                    <div class="col-md-2" id="logoEnTete">
                        <a href="index.php"><img src="../img/ACCut.png" alt="Logo-AC"></a>
                    </div>
                    <div id="titreSecondaire" class="col-md-5">    
                        <p>- Naturopathie & Reïki -</p>
                    </div>
                </div>    
            </div>
        
            <nav>
                <div class="container" id='espaceP'>
                    <div class="row">
                        <div class="col-md-12">
                            <ul>
                                <?php $userSession = new UserSession(); ?> 
                                    <?php if($userSession->isAuthenticated() == true): ?>
                                        <li class='red'>
                                            <div class="toggle">
                                                <p class="welcome"><i class="fas fa-sort-down"></i> Bonjour <strong><?= htmlspecialchars($userSession->getName()) ?></strong></p>  
                                                <div class="menu">
                                                    <ul class="listeMenu">
                                                        <li><a href="index.php">Retour au site</a></li>
                                                        <li class='red'><a href="logout.php">Se déconnecter</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>                     
                                    <?php else : ?>
                                        <li class='red'><a href="connexion.php">Se connecter</a></li>          
                                    <?php endif; ?> 
                                <li><a class="js-scrollTo" href="#rendezVous">Mes Rendez-vous</a></li>
                                <li><a class="js-scrollTo" href="#resume">Résumé de consultation</a></li>                        
                                <li><a class="blog" href="">Blog</a></li>
                            </ul>
                        </div>
                    </div>
                </div>    
            </nav>
        </header> 

        <div class="rouleau">
            <!-- MES RDV  -->
            <section id="rendezVous" class="container">
                <h3>Mes rendez-vous</h3>
                    <?php foreach($mesRdv as $rendezVous): ?>
                        <?php if ($rendezVous['date'] < $rendezVous['thisDay']):?>
                            <li class='past'> <a href> &#x2022 <?= $rendezVous['name']?> le <?=$rendezVous['dateEu']?> à <?=$rendezVous['start_hour'] ?> </a></li>
                        <?php else: ?>
                            <li> <a href> &#x2022 <?= $rendezVous['name']?> le <?=$rendezVous['dateEu']?> à <?=$rendezVous['start_hour'] ?> </a></li>
                        <?php endif; ?>   
                    <?php endforeach; ?>
            </section>
            <!-- PRENDRE RDV -->
            <section id="resume" class="container">
                <h3>Résumé de consultation</h3>
                
            </section>
        </div> <!--  fin de rouleau -->
        <script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>
        <script src="../js/function.js"></script>
        <script src="../js/main.js"></script>
    </body>
</html>