<?php include "templates/head.phtml" ?>
    <body> 
        <header>
            <div class="container">
                <div class="row">
                    <div id="titrePrimaire" class="col-md-5">
                        <h1>Aurélie Contamine</h1>
                    </div>
                    <div class="col-md-2" id="logoEnTete">
                        <a href="index.php"><img src="../img/ACCut.png" alt="Logo-AC"></a>
                    </div>
                    <div id="titreSecondaire" class="col-md-5">    
                        <p>- Naturopathie & Reïki -</p>
                    </div>
                </div>    
            </div>
        
            <nav>
                <div class="container" id='espaceP'>
                    <div class="row">
                        <div class="col-md-12">
                            <ul>
                                <?php $userSession = new UserSession(); ?> 
                                    <?php if($userSession->isAuthenticated() == true): ?>
                                        <li class='red userTag'>
                                            <div class="toggle">
                                                <p class="welcome"><i class="fas fa-sort-down"></i> Bonjour <strong><?= htmlspecialchars($userSession->getName()) ?></strong></p>  
                                                <div class="menu">
                                                    <ul class="listeMenu">
                                                        <li><a href="index.php">Retour au site</a></li>
                                                        <li class='red'><a href="logout.php">Se déconnecter</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>                     
                                    <?php else : ?>
                                        <li class='red userTag'><a href="connexion.php">Se connecter</a></li>          
                                    <?php endif; ?> 
                                    <div class="hamb">
                                        <li class='hamburger inactif'><i class="fas fa-bars"></i></li> 
                                    </div>
                                <li class='menus'><a class="js-scrollTo" href="#rendezVous">Mes Rendez-vous</a></li>
                                <li class='menus'><a class="js-scrollTo" href="#resume">Résumé de consultation</a></li>                        
                                <li class='menus'><a class="blog" href="">Blog</a></li>
                            </ul>
                        </div>
                    </div>
                </div>    
            </nav>
        </header> 

        <div class="rouleau">
            <!-- MES RDV  -->
            <section id="rendezVous" class="container">
                <h3>Mes rendez-vous</h3>
                    <li>
                        <?php foreach($mesRdv as $rendezVous): ?>
                            <?php if ($rendezVous['date'] < $rendezVous['thisDay']):?>
                                <ul class='past'> <a href="" class='rdv-espacePerso'> &#x2022 <?= $rendezVous['name']?> le <?=$rendezVous['dateEu']?> à <?=$rendezVous['hourEU'] ?><div class="inactif"><?=$rendezVous['content']?></div> </a></ul>
                            <?php else: ?>
                                <ul> <a href="" class='rdv-espacePerso'> &#x2022 <?= $rendezVous['name']?> le <?=$rendezVous['dateEu']?> à <?=$rendezVous['hourEu'] ?><div class="inactif"><?=$rendezVous['content']?></div> </a></ul>
                            <?php endif; ?>   
                        <?php endforeach; ?>
                    </li>
            </section>
            <!-- RESUME -->
            <section id="resume" class="container">
                <h3>Résumé de consultation</h3>
                    <div class="fichePatient-content">
                        
                    </div>
            </section>
        </div> <!--  fin de rouleau -->
        <script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>
        <script src="../js/function.js"></script>
        <script src="../js/main.js"></script>
    </body>
</html>