<?php include "templates/head.phtml" ?>
    <body> 
        <header>
            <div class="container">
                <div class="row">
                    <div id="titrePrimaire" class="col-md-5">
                        <h1>Aurélie Contamine</h1>
                    </div>
                    <div class="col-md-2" id="logoEnTete">
                        <a href="index.php"><img src="../img/ACCut.png" alt="Logo-AC"></a>
                    </div>
                    <div id="titreSecondaire" class="col-md-5">    
                        <p>- Naturopathie & Reïki -</p>
                    </div>
                </div>    
            </div>
        
            <nav>
                <div class="container" id='espaceP'>
                    <div class="row">
                        <div class="col-md-12">
                            <ul>
                                <?php $userSession = new UserSession(); ?> 
                                    <?php if($userSession->isAuthenticated() == true): ?>
                                        <li class='red'>
                                            <div class="toggle">
                                                <p class="welcome"><i class="fas fa-sort-down"></i> Bonjour <strong><?= htmlspecialchars($userSession->getName()) ?></strong></p>  
                                                <div class="menu">
                                                    <ul class="listeMenu">
                                                        <li><a href="index.php">Retour au site</a></li>
                                                        <li class='red'><a href="logout.php">Se déconnecter</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>                     
                                    <?php else : ?>
                                        <li class='red'><a href="connexion.php">Se connecter</a></li>          
                                    <?php endif; ?> 
                                <li><a class="js-scrollTo" href="espaceAdmin.php">Mes Rendez-vous</a></li>
                                <li><a class="js-scrollTo" href="patientele.php"> Fiche Patientèle</a></li>                             
                                <li><a class="blog" href="">Blog</a></li>
                            </ul>
                        </div>
                    </div>
                </div>    
            </nav>
        </header> 

        <div class="rouleau">
            <section class="container">
                <div class="row">
                    <div class="col-md-6">
                    <h3>Fiche de renseignement<br><a href="editUser.php?id= <?= $userInfo['user_id']; ?>" style="font-family: Arial; font-size: 1rem; color: black;">(modifier)</a></h3>
                        <p> <strong>Nom : </strong><?= $userInfo['lastName']; ?><br>
                            <strong>Prenom : </strong><?= $userInfo['firstName']; ?><br>
                            <strong>Date de naissance : </strong><?= $userInfo['dateEu']; ?><br>
                            <strong>Sexe : </strong><?= $userInfo['sex']; ?><br>
                            <strong>Taille : </strong><?= $userInfo['height']; ?><br>
                            <strong>Poids : </strong><?= $userInfo['weight']; ?><br>
                            <strong>Régime : </strong><?= $userInfo['diet']; ?></p>
                        <p> <strong>Email : </strong><?= $userInfo['email']; ?><br>
                            <strong>Téléphone : </strong><?= $userInfo['phone']; ?></p>
                        <p> <strong>Raison de la venue : </strong><?= $userInfo['reason']; ?></p>
                        <p> <strong>Pathologies : </strong><?= $userInfo['pathology']; ?><br>
                            <strong>Traitements : </strong><?= $userInfo['treatment']; ?></p>
                        <p> <strong>Emonctoires : </strong><?= $userInfo['emunctory']; ?></p>
                        <p> <strong>Autres informations : </strong><?= $userInfo['other']; ?></p>

                        <h3>Rendez-vous :</h3>
                            <li>
                                <?php foreach($mesRdv as $rendezVous): ?>
                                    <?php if ($rendezVous['date'] < $rendezVous['thisDay']):?>
                                        <ul class='past'> <a href="" class="rdv-fichePatient" id=<?= $rendezVous['rdv_id']?>> &#x2022 <?= $rendezVous['name']?> le <?=$rendezVous['dateEu']?> à <?=$rendezVous['start_hour'] ?><div class="inactif"><?=$rendezVous['content']?></div></a></ul>   
                                    <?php else: ?>
                                        <ul> <a href="" class="rdv-fichePatient" id=<?= $rendezVous['rdv_id']?>> &#x2022 <?= $rendezVous['name']?> le <?=$rendezVous['dateEu']?> à <?=$rendezVous['start_hour'] ?><div class="inactif"><?=$rendezVous['content']?></div></a></ul>
                                    <?php endif; ?>   
                                <?php endforeach; ?>
                            </li>
                    </div>
                    <div class="col-md-6">
                        <div class="fichePatient-content">
                        
                        </div>
                    </div>
                </div> 
            </section>
        </div> <!--  fin de rouleau -->
        <script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>
        <script src="../js/function.js"></script>
        <script src="../js/main.js"></script>
    </body>
</html>