<?php include "templates/head.phtml" ?>
    <body> 
    <?php include "templates/headerAdmin.phtml" ?> 

        <div class="rouleau">
            <section class="container">
                <div class="row">
                    <div class="col-md-6">
                    <h3>Fiche de renseignement<br><a href="editUser.php?id=<?=$userInfo['user_id'];?>" style="font-family: Arial; font-size: 1rem; color: black;">(modifier)</a></h3>
                        <p> <strong>Nom : </strong><?= htmlspecialchars($userInfo['lastName']); ?><br>
                            <strong>Prenom : </strong><?= htmlspecialchars($userInfo['firstName']); ?><br>
                            <strong>Date de naissance : </strong><?= $userInfo['dateEu']; ?><br>
                            <strong>Sexe : </strong><?= htmlspecialchars($userInfo['sex']); ?><br>
                            <strong>Taille : </strong><?= htmlspecialchars($userInfo['height']); ?><br>
                            <strong>Poids : </strong><?= htmlspecialchars($userInfo['weight']); ?><br>
                            <strong>Régime : </strong><?= htmlspecialchars($userInfo['diet']); ?></p>
                        <p> <strong>Email : </strong><?= htmlspecialchars($userInfo['email']); ?><br>
                            <strong>Téléphone : </strong><?= htmlspecialchars($userInfo['phone']); ?></p>
                        <p> <strong>Raison de la venue : </strong><?= htmlspecialchars($userInfo['reason']); ?></p>
                        <p> <strong>Pathologies : </strong><?= htmlspecialchars($userInfo['pathology']); ?><br>
                            <strong>Traitements : </strong><?= htmlspecialchars($userInfo['treatment']); ?></p>
                        <p> <strong>Emonctoires : </strong><?= htmlspecialchars($userInfo['emunctory']); ?></p>
                        <p> <strong>Autres informations : </strong><?= htmlspecialchars($userInfo['other']); ?></p>

                        <h3>Rendez-vous :</h3>
                            <li>
                                <?php foreach($mesRdv as $rendezVous): ?>
                                    <?php if ($rendezVous['date'] < $rendezVous['thisDay']):?>
                                        <ul class='past'> <a href="" class="rdv-fichePatient" id=<?= $rendezVous['rdv_id']?>> &#x2022 <?= $rendezVous['name']?> le <?=$rendezVous['dateEu']?> à <?=$rendezVous['hourEu'] ?><div class="inactif"><?= htmlspecialchars($rendezVous['content'])?></div></a></ul>   
                                    <?php else: ?>
                                        <ul> <a href="" class="rdv-fichePatient" id=<?= $rendezVous['rdv_id']?>> &#x2022 <?= $rendezVous['name']?> le <?=$rendezVous['dateEu']?> à <?=$rendezVous['hourEu'] ?><div class="inactif"><?=htmlspecialchars($rendezVous['content'])?></div></a></ul>
                                    <?php endif; ?>   
                                <?php endforeach; ?>
                            </li>
                    </div>
                    <div class="col-md-6">
                        <div class="fichePatient-content">
                        
                        </div>
                    </div>
                </div> 
            </section>
        </div> <!--  fin de rouleau -->
        <script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>
        <script src="../js/function.js"></script>
        <script src="../js/main.js"></script>
    </body>
</html>