<?php include "templates/head.phtml" ?>
    <body> 
        <header>
            <div class="container">
                <div class="row">
                    <div id="titrePrimaire" class="col-md-5">
                        <h1>Aurélie Contamine</h1>
                    </div>
                    <div class="col-md-2" id="logoEnTete">
                        <a href="index.php"><img src="../img/ACCut.png" alt="Logo-AC"></a>
                    </div>
                    <div id="titreSecondaire" class="col-md-5">    
                        <p>- Naturopathie & Reïki -</p>
                    </div>
                </div>    
            </div>
        
            <nav>
                <div class="container" id='espaceP'>
                    <div class="row">
                        <div class="col-md-12">
                            <ul>
                                <?php $userSession = new UserSession(); ?> 
                                    <?php if($userSession->isAuthenticated() == true): ?>
                                        <li class='red'>
                                            <div class="toggle">
                                                <p class="welcome"><i class="fas fa-sort-down"></i> Bonjour <strong><?= htmlspecialchars($userSession->getName()) ?></strong></p>  
                                                <div class="menu">
                                                    <ul class="listeMenu">
                                                        <li><a href="index.php">Retour au site</a></li>
                                                        <li class='red'><a href="logout.php">Se déconnecter</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>                     
                                    <?php else : ?>
                                        <li class='red'><a href="connexion.php">Se connecter</a></li>          
                                    <?php endif; ?> 
                                <li><a class="js-scrollTo" href="espaceAdmin.php">Mes Rendez-vous</a></li>
                                <li><a class="js-scrollTo" href="patientele.php"> Fiche Patientèle</a></li>                             
                                <li><a class="blog" href="">Blog</a></li>
                            </ul>
                        </div>
                    </div>
                </div>    
            </nav>
        </header> 

        <div class="rouleau">
            <!-- MES RDV  -->
            <section class="container">
                <h3>Fiche de renseignement<br><a href="editUser.php?id= <?= $userInfo['0']['user_id']; ?>" style="font-family: Arial; font-size: 1rem; color: black;">(modifier)</a></h3>
                <p>Nom : <?= $userInfo['0']['lastName']; ?><br>Prenom : <?= $userInfo['0']['firstName']; ?><br>Age : <?= $userInfo['0']['age']; ?><br>Sexe : <?= $userInfo['0']['sex']; ?><br>Taille : <?= $userInfo['0']['height']; ?><br>Poids : <?= $userInfo['0']['weight']; ?><br>Régime : <?= $userInfo['0']['diet']; ?></p>
                <p>Email : <?= $userInfo['0']['email']; ?><br>Téléphone : <?= $userInfo['0']['phone']; ?></p>
                <p>Raison de la venu : <?= $userInfo['0']['reason']; ?></p>
                <p>Pathologies : <?= $userInfo['0']['pathology']; ?><br>Traitements : <?= $userInfo['0']['treatment']; ?></p>
                <p>Emonctoires : <?= $userInfo['0']['emunctory']; ?></p>
                <p>Autres informations : <?= $userInfo['0']['other']; ?></p>

            </section>
        </div> <!--  fin de rouleau -->
        <script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>
        <script src="../js/function.js"></script>
        <script src="../js/main.js"></script>
    </body>
</html>