<?php include "templates/head.phtml" ?>
    <body>   
    <!-- HEADER & NAV     -->
    <?php include "templates/header.phtml" ?>
    <div class="rouleau">
    <!-- PRESENTATION -->
        <section id="presentation" class="container presentation">
            <article class="row ">
                <div class="col-md-3">
                    <img src="../img/aurelie.jpg" alt="photo-AC">
                </div>
                <div class="col-md-9">
                    <h3>Qui suis-je ?</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque inventore corrupti laborum, ea iure suscipit eligendi veritatis maxime, quas optio perferendis numquam. Totam omnis sequi eligendi obcaecati repellat maiores illum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique odio rerum unde? Numquam enim recusandae nisi aut animi dolorum dignissimos. Quod facilis sit, minus delectus eum molestias suscipit inventore sapiente.</p>
                </div>
            </article>
            <article class="row">
                <div class="col-md-9">
                    <h3>Mon parcours</h3>
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Porro quo dicta sapiente soluta autem esse, veniam sed temporibus at ipsa eos sunt quibusdam quaerat sit nisi quae alias facere cum? Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem quo temporibus, fugiat odio sunt nostrum voluptates accusamus iste vitae perspiciatis! Corporis iusto sunt quidem. Illum omnis animi reiciendis voluptates ad.</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque inventore corrupti laborum, ea iure suscipit eligendi veritatis maxime, quas optio perferendis numquam. Totam omnis sequi eligendi obcaecati repellat maiores illum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique odio rerum unde? Numquam enim recusandae nisi aut animi dolorum dignissimos.</p>
                </div>
                <div class="col-md-3">
                    <img src="https://media.giphy.com/media/l378mwOYgL6NaCZIk/giphy.gif" alt="illustration">
                </div>
            </article>
        </section>
    <!-- NATURO -->
        <section id="naturo" class="container naturo">
            <h2>La Naturopathie</h2>
                <div class="row">
                    <div class="col-md-12">
                        <h3>Que'est ce que c'est ?</h3>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt voluptates minima laborum aliquid architecto iste commodi esse necessitatibus cumque dolores! Ipsa odio quis iure accusamus, eveniet saepe porro reiciendis? Porro. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, repellendus dolore, eaque fuga voluptates distinctio et amet, eos odio iste ea numquam expedita sed ipsam dignissimos esse officia quas architecto.</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit adipisci ratione, veniam commodi corrupti nostrum vel eos iste molestiae ipsam, quibusdam reprehenderit. Id atque libero voluptas, eos in aperiam quaerat.</p>
                    </div>

                    <div class="col-md-12">
                        <h3>Comment ca se passe ?</h3>
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laborum impedit cum inventore molestias delectus illum rerum, nesciunt, enim ab non veniam doloribus earum omnis nobis quis quas? Dicta, enim suscipit.</p>
                        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vel, molestias labore praesentium culpa quam explicabo sapiente ullam consectetur fuga quod delectus? Architecto, autem iure? Nulla nisi ut dolores veniam quibusdam? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni sunt possimus dolorum, dolorem ut sapiente adipisci molestiae perspiciatis minus quibusdam sed! Corrupti doloremque, ex eum nobis nesciunt impedit atque ullam.</p>
                    </div>
                </div>
        </section>        
    <!-- METHODES -->
        <section id="methodes" class="container methodes">
            <h2>Methodes</h2>
                <div class="row methode">
                    <div> 
                        <a href="fdb.php"><img  srcset="../img/methodes/FdB-mini.jpg w400,
                                                        ../img/methodes/FdB.jpg w800"
                                                sizes="(max-width: 767px) 300px,
                                                       700px"
                                                src="../img/methodes/FdB.jpg" alt="Fleurs de Bach"></a>
                    </div>
                    <div>
                        <a href="alimentation.php"><img src="../img/methodes/Alimentation.jpg" alt="Alimentation"></a>
                    </div>
                    <div>
                        <a href="huileEss.php"><img src="../img/methodes/HE.jpg" alt="Huiles essentielles"></a>
                    </div>
                    <div>
                        <a href="litho.php"><img src="../img/methodes/Litho.jpg" alt="Lithothérapie"></a>
                    </div> 
                </div>
        </section>
    <!-- REIKI -->
        <section id="reiki" class="container reiki">
            <h2>Le Reïki</h2>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Id maxime molestiae ullam suscipit assumenda error voluptate mollitia tempore esse totam doloremque fuga libero asperiores deserunt dolorum voluptatem, fugiat hic. Ipsa! Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque laborum corporis molestias sed animi, asperiores id nulla veritatis culpa. Ipsum, in nihil! Praesentium fugit hic aliquid, aspernatur incidunt nisi quidem?</p>
                <img src="../img/reiki.png" alt="reiki">
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto in modi autem vel, cumque, est commodi ea facere neque vero labore voluptatum at ut quod tenetur a expedita eos dolore.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore nostrum adipisci impedit placeat a rerum aliquid sapiente omnis libero! Iure nihil culpa dolores maiores ex maxime numquam amet a tempora. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fugiat in praesentium blanditiis facilis totam quisquam dolor, a, aspernatur vel aut voluptatibus quaerat pariatur tenetur at dolorum illum consequuntur distinctio nisi.</p>
        </section>
    <!-- TARIFS -->
        <section id="tarifs" class="container tarifs">
            <h2>Les Tarifs</h2>
                <h3>Naturopathie</h3>
                    <table>
                        <tbody>
                            <tr>
                                <td>- 1ère séance</td>
                                <td>1H30</td>
                                <td>60€</td>
                            </tr>
                            <tr>
                                <td>- Séance suivante</td>
                                <td>1H</td>
                                <td>45€</td>
                            </tr>
                        </tbody>
                    </table> 
                <h3>Reïki</h3>
                    <table>
                        <tbody>
                            <tr>
                                <td>- Soin reïki</td>
                                <td>30min</td>
                                <td>30€</td>
                            </tr>
                            <tr>
                                <td>- Soin reïki</td>
                                <td>45min</td>
                                <td>40€</td>
                            </tr>
                            <tr>
                                <td>- Soin reïki</td>
                                <td>60min</td>
                                <td>50€</td>
                            </tr>
                        </tbody>
                    </table>
        </section>
    <!-- CONTACT -->
        <section id="contact" class="container contact">
            <h2>Me contacter</h2>
            <div class="row">
                <div class="col-md-6 infoContact">
                    <div class="adresse">
                        <h4>Aurélie Contamine</h4>
                        <p>20 rue Turenne<br>52600 Chalindrey</p>
                        <p>07.69.12.39.94</p>
                        <p>aurelie.c.naturopathe@gmail.com</p>
                    </div>
                    <div id="map"></div>
                </div>
                <div class="col-md-6">
                <form action="contact.php" name="contact_form" method="POST">
                <?php if (!empty($_GET['success'])) : ?>
                    <div class="alert alert-success" role="alert"><?= $_GET['success'] ?></div>
                <?php elseif (!empty($_GET['err'])) : ?>
                    <div class="alert alert-danger" role="alert"><?= $_GET['err'] ?></div>
                <?php endif; ?>
                    <div class="demi">
                        <input type="text" id="firstName" name="firstName" placeholder="Prénom" requiered>
                        <input type="text" id="lastName" name="lastName" placeholder="Nom" requiered>
                    </div>
                    <input type="text" id="email" name="email" placeholder="email" requiered>
                    <textarea name="message" id="message" cols="30" rows="10" placeholder="Ecrivez ici votre message" requiered></textarea>
                    <input type="submit" class="submit btn-Form" value="Envoyer">           
                </form>
                </div>
            </div>
        </section>
        
    </div> <!-- fin rouleau -->
    <script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                macarte = L.map('map').setView([47.8034, 5.42869], 12);
                // Leaflet ne récupère pas les cartes (tiles) sur un serveur par défaut. Nous devons lui préciser où nous souhaitons les récupérer. Ici, openstreetmap.fr
                L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png', {
                        // Il est toujours bien de laisser le lien vers la source des données
                        attribution: '© <a href="//osm.org/copyright">OpenStreetMap</a>',
                        minZoom: 1,
                        maxZoom: 20
                    }).addTo(macarte);
                var myIcon = L.icon({
                    iconUrl: "../img/ACmap.svg",
                    iconSize: [80, 95],
                    iconAnchor: [40, 90],
                    popupAnchor: [-3, -76],
                });
                var marker = L.marker([47.8034, 5.42869], { icon: myIcon }).addTo(macarte);
            })
    </script>
        
        <script src="../js/function.js"></script>
        <script src="../js/main.js"></script>
    </body>
</html>
