<?php include "templates/head.phtml" ?>
    <body>   
    <?php include "templates/headerMethodes.phtml"?>
    <div class="image">
        <div class="metho">
            <section id="" class="container">
                <h2 class='titre_methode'>Lithothérapie</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, temporibus earum. Quisquam adipisci officiis, deserunt recusandae dicta sapiente impedit ut eius natus cumque atque magnam beatae labore maiores, minus eaque Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus aspernatur et doloremque iste. Saepe atque dolor vitae labore maxime debitis, modi sequi ab nostrum sit ex asperiores ducimus porro rem.</p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odit placeat atque error! Iste velit incidunt voluptatibus quia, repellat itaque ratione soluta tempora, doloremque laborum optio non fugiat laudantium consequatur vitae.</p>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nobis ut illo nesciunt eum qui suscipit tempora magni. Facere, sequi quidem. Saepe voluptates, reiciendis excepturi ipsam doloribus minima. Tenetur, quisquam itaque.<br>
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Velit reiciendis, cupiditate distinctio voluptates delectus nam ad, accusamus voluptatum et totam doloribus mollitia nulla ea, doloremque corporis aliquam quod reprehenderit harum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore enim quas distinctio mollitia debitis in id vitae nostrum nesciunt vero harum quibusdam, officiis quod consequuntur ducimus at? Explicabo, ducimus veniam!</p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nostrum repellat ipsa optio. Sequi, recusandae molestias, tempore mollitia necessitatibus aperiam nesciunt harum maxime inventore eum, veniam adipisci totam similique iste dolorem.</p>

            </section>
        </div> 
    </div>
    <script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>
    <script src="../js/function.js"></script>
    <script src="../js/main.js"></script>
    </body>
</html>
