<?php include "templates/head.phtml" ?>
    <body> 
    <?php include "templates/headerAdmin.phtml" ?>

        <div class="rouleau">
            <section class="container">
                <h3>Resumé de consultation</h3>
                <form action='saveReport.php?id=<?=$content['rdv_id']?>' method='post'>
                    <textarea name="modifResume" id="modifResume" cols="30" rows="20"><?=htmlspecialchars($content['content'])?></textarea>
                    <input class='submit' type='submit' value='Enregistrer'>
                </form>
            </section>
        </div> <!--  fin de rouleau -->
        <script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>
        <script src="../js/function.js"></script>
        <script src="../js/main.js"></script>
    </body>
</html>