<?php include "templates/head.phtml" ?>
    <body> 
    <?php include "templates/headerAdmin.phtml" ?>

    <div class="rouleau">
            <!-- MES RDV  -->
            <section class="container">
                <h3>Fiche patientèle<br><a href="#" style="font-family: Arial; font-size: 1rem; color: black;">(Ajouter une fiche)</a></h3>
            </section>
        </div> <!--  fin de rouleau -->
        <script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>
        <script src="../js/function.js"></script>
        <script src="../js/main.js"></script>
    </body>
</html>