<!-- Page d'ajout d'un article -->
<h2>Rédiger un nouvel article</h2>

<!-- Formulaire de saisie d'un nouvel article -->
<form class="formulaire" action="add_post.php" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Nouvel article</legend>
        <ul>
            <li>
                <label for="title">Titre :</label>
                <input type="text" id="title" name="title">
            </li>
            <li>
                <label class="textarea" for="content">Article :</label>
                <textarea id="content" name="content" rows="15"></textarea>
            </li>
    
            <li>
                <label for="category">Catégorie :</label>
                <select id="category" name="category">
                    <?php foreach($categories as $category): ?>
                        <option value="<?= htmlspecialchars($category['Id']) ?>"><?= htmlspecialchars($category['Name']) ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <li>
                <div class="buttons">
                    <button class="submit btn-Form send" type="submit">Enregistrer</button>
                    <a class="submit btn-Form cancel" href="admin.php">Annuler</a>
                </div>
            </li>
        </ul>
    </fieldset>
</form>