<!-- Page d'édition d'un article -->
<h2><i class="fa fa-pencil"></i> Editer un article</h2>

<!-- Formulaire de mise à jour d'un article -->
<form class="formulaire" action="edit_post.php" method="post">

    <!-- Utilisation d'un champ caché pour spécifier à quel article rattacher le commentaire -->
    <input type="hidden" name="postId" value="<?= $postId ?>">

    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Article</legend>
        <ul>
            <li>
                <label for="title">Titre :</label>
                <input type="text" id="title" name="title" value="<?= htmlspecialchars($post['Title']) ?>">
            </li>
            <li>
                <label class="textarea" for="contents">Article :</label>
                <textarea id="content" name="content" rows="15"><?= htmlspecialchars($post['Content']) ?></textarea>
            </li>
            <li>
                <div class="buttons">
                    <button class="submit btn-Form send" type="submit">Mettre à jour</button>
                    <a class="submit btn-Form cancel" href="admin.php">Annuler</a>
                </div>
            </li>
        </ul>
    </fieldset>
</form>