<!-- Page d'accueil -->
<h2><i class="fa fa-home"></i> Accueil</h2>

<!-- Liste des articles du blog -->
<ul class="post-list">
    <?php foreach($posts as $post): ?>
        <li class="post">
            <h3>
                <i class="fab fa-pagelines"></i>&nbsp;
                
                <a href="show_post.php?id=<?= $post['Id'] ?>" title="Consulter l'article">
                    <?= htmlspecialchars($post['Title']) ?>
                </a>
            </h3>
            
            <article><?= substr(htmlspecialchars($post['Content']), 0, 100) ?>&nbsp;[...]</article>
            <small>
                Rédigé par Aurélie Contamine 
                le <?= $post['CreationTimestamp'] ?>
            </small>
        </li>
    <?php endforeach; ?>
</ul>